research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledge reports with the mains topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst

extract_chats_task:
  description: >
    Extract the list of available chats from WhatsApp Web.
    Use the WhatsApp Selenium Tool to navigate and extract chat information.
  expected_output: >
    A list of available chats with their names and any additional metadata.
  agent: researcher

extract_messages_task:
  description: >
    Extract messages from the specified chat using the chat name provided.
    Navigate to the chat and collect all available messages with their timestamps.
  expected_output: >
    A detailed list of messages with timestamps and sender information,
    formatted in a clean and readable manner.
  agent: researcher

process_data_task:
  description: >
    Process the extracted WhatsApp messages and generate insights.
    Analyze patterns, identify key conversations, and organize the data.
  expected_output: >
    A structured report containing processed chat data with key insights,
    patterns, and notable conversations. Format as JSON for further processing.
  agent: data_processor
